TPI-ProjectPresenter/Models/DAO/Project.cs
using System;
using System.Collections.Generic;

namespace TPI_ProjectPresenter.Models.DAO;

public partial class Project
{
    public int Pid { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Tooltip { get; set; }

    public string? ImgRef { get; set; }

    public virtual ICollection<ProjectTab> ProjectTabs { get; set; } = new List<ProjectTab>();
}

TPI-ProjectPresenter/Models/Projects/ProjectEntity.cs
namespace TPI_ProjectPresenter.Models.Projects
{
    public class ProjectEntity
    {
        public int PID { get; set; }
        public ProjectHeader Header { get; set; }

        List<ProjectTab>? _Tabs;

        public ProjectEntity() 
        {
            PID = 0;
            _Tabs = new List<ProjectTab>();
            Header = new ProjectHeader();
        }

        public ProjectEntity(int pPID, string pName, string pDescription, string pToolTip, string pImgRef) : this()
        {
            PID = pPID;
            Header.ProjectName = pName;
            Header.ProjectDescription = pDescription;
            Header.ProjectTooltip = pToolTip;
            Header.ProjectImgRef = pImgRef;
        }

        public class ProjectHeader
        {
            public string? ProjectName { get; set; }
            public string? ProjectDescription { get; set; }
            public string? ProjectTooltip { get; set; }
            public string? ProjectImgRef { get; set; }
        }

        public void AddTab(ProjectTab tab)
        {
            _Tabs.Add(tab);
        }

        public ProjectTab GetFirstTab()
        {
            return _Tabs.FirstOrDefault();
        }

        public List<ProjectTab> GetTabs()
        {
            return _Tabs;
        }
    }
}

TPI-ProjectPresenter/Models/Projects/ProjectTab.cs
using TPI_ProjectPresenter.Models.ProjectContent;

namespace TPI_ProjectPresenter.Models.Projects
{
    public class ProjectTab
    {
        public int TID { get; private set; }
        public string TabName { get; set; }
        List<ContentSection>? _Sections { get; set; }

        public ProjectTab() 
        {
            _Sections = new List<ContentSection>();
        }

        public ProjectTab(int pTID, string pTabName) : this()
        {
            TID = pTID;
            TabName = pTabName;
        }

        public void AddSection(ContentSection section)
        {
            _Sections.Add(section);
        }

        public ContentSection GetFirstSection()
        {
            return _Sections.FirstOrDefault();
        }

        public List<ContentSection> GetSections()
        {
            return _Sections;
        }
    }
}

TPI-ProjectPresenter/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;
using NuGet.Versioning;
using System.IO;
using TPI_ProjectPresenter.DataAdapters;
using TPI_ProjectPresenter.Models.DAO;
using TPI_ProjectPresenter.Models.DataTx;
using TPI_ProjectPresenter.Models.ProjectContent;
using TPI_ProjectPresenter.Models.Projects;
using static System.Collections.Specialized.BitVector32;

namespace TPI_ProjectPresenter.Controllers
{
	public class ProjectController : Controller
	{
        private readonly ProjectPresenterPwaContext _DBContext;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProjectController(ProjectPresenterPwaContext dbContext, IWebHostEnvironment _webHostEnvironment)
        {
            _DBContext = dbContext;
            this.webHostEnvironment = _webHostEnvironment;
        }

        public string UploadImage(IFormFile pImgFile)
        {
            string fileName = null;
            if (pImgFile != null)
            {
                string uploadDir = Path.Combine(webHostEnvironment.WebRootPath, "img");
                fileName = Guid.NewGuid().ToString().Substring(0, 15) + "-" + pImgFile.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var filestream = new FileStream(filePath, FileMode.Create))
                {
                    pImgFile.CopyTo(filestream);
                }
            }
            return fileName;
        }
        

        [HttpGet]
        public IActionResult NewProject()
        {
            var aux = new ViewProjectEntityData() { ProjectData = new ProjectEntity() };


            return View(aux);
        }

        [HttpPost]
        public IActionResult NewProject(ViewProjectEntityData np)
        {
            var aux = _DBContext.Projects.OrderByDescending(p => p.Pid).ToList();

            if (aux.Count() != 0) { np.ProjectData.PID = aux.FirstOrDefault().Pid + 1; }
            else { np.ProjectData.PID = 1; }

            string filename = UploadImage(np.ImgFile);
            np.ProjectData.Header.ProjectImgRef = filename;

            var prow = ProjectDataAdapter.ProjectRowFromObject(np.ProjectData);

            _DBContext.Projects.Add(prow);
            _DBContext.SaveChanges();


            return RedirectToAction("ViewProject", new {ppid = np.ProjectData.PID});
        }


        [HttpPost]
        public IActionResult NewTab(string TabName = "", int PID = 0)
        {

            var tabCount = _DBContext.ProjectTabs.Where(t => t.Pid == PID).OrderByDescending(p => p.Tid);
            int TID = tabCount.First().Tid+1;
            _DBContext.ProjectTabs.Add(new Models.DAO.ProjectTab() { Pid = PID, Tid = TID, Name = TabName });

            _DBContext.SaveChanges();
            return RedirectToAction($"ViewProject", new { ppid = PID, ptid = TID });
        }

        [HttpGet]
        public IActionResult NewSection(int pPID, int pTID)
        {
            var aux = new ViewSectionData();
            aux.PID = pPID;
            aux.TID = pTID;

            return View(aux);
        }
        [HttpPost]
        public IActionResult NewSection(ViewSectionData data)
        {
            var aux = _DBContext.ContentSections.Where(p => p.Pid == data.PID && p.Tid == data.TID).OrderByDescending(p => p.Sid).ToList();
            int SID;
            if (aux.Count > 0) { SID = aux.FirstOrDefault().Sid + 1; }
            else { SID = 1; }

            var newSection = ContentSectionDataAdapter.SectionRowFromObject(data.section);
            newSection.Sid = SID;
            newSection.Pid = data.PID;
            newSection.Tid = data.TID;

            _DBContext.ContentSections.Add(newSection);
            _DBContext.SaveChanges();

            return RedirectToAction("ViewProject", new { ppid =  data.PID, ptid = data.TID });
        }

        [HttpGet]
        public IActionResult NewItem(int pPID, int pTID, int pSID)
        {
            var aux = new ViewItemData();
            aux.PID = pPID;
            aux.TID = pTID;
            aux.SID = pSID;
            return View(aux);
        }
        [HttpPost]
        public IActionResult NewItem(ViewItemData data)
        {
            var aux = _DBContext.ContentItems.Where(p => p.Pid == data.PID && p.Tid == data.TID && p.Sid == data.SID).OrderByDescending(p => p.Iid).ToList();
            int IID;
            if (aux.Count > 0) { IID = aux.FirstOrDefault().Iid + 1; }
            else { IID = 1; }

            if (data.ItemData.ItemType == "SingleImage")
            {
                var imgAux = new Models.ProjectContent.ContentItemSingleImage();
                imgAux.ImageRef = UploadImage(data.ImgFile);
                imgAux.IID = IID;
                imgAux.ItemTitle = data.ItemData.ItemTitle;
                imgAux.ItemText = data.ItemData.ItemText;
                
                data.ItemData = imgAux;
            }
            if (data.ItemData.ItemType == "SingleComparison")
            {
                string[] lItemInfo = [Request.Form["LItemInfo1"], Request.Form["LItemInfo2"], Request.Form["LItemInfo3"]];
                string[] rItemInfo = [Request.Form["RItemInfo1"], Request.Form["RItemInfo2"], Request.Form["RItemInfo3"]];
                data.SingleComparisonData.LeftItem.SetInfoFromArray(lItemInfo);
                data.SingleComparisonData.RightItem.SetInfoFromArray(rItemInfo);
            }

            var newItem = ContentItemDataAdapter.ItemRowFromDataObject(data);
            newItem.Iid = IID;
            newItem.Pid = data.PID;
            newItem.Tid = data.TID;
            newItem.Sid = data.SID;
            _DBContext.ContentItems.Add(newItem);
            _DBContext.SaveChanges();
            return RedirectToAction("ViewProject", new { ppid = data.PID, ptid = data.TID });
        }

        [HttpGet]
        public IActionResult EditProject(int pPID)
        {
            var prj = _DBContext.Projects.Find(pPID);
            if (prj == null) return NotFound();
            var prjObj = ProjectDataAdapter.ProjectHeaderFromProject(prj);
            var aux = new ViewProjectEntityData() { ProjectData = prjObj };
            return View(aux);
        }

        [HttpPost]
        public IActionResult EditProject(ViewProjectEntityData pData)
        {
            var prj = _DBContext.Projects.Find(pData.ProjectData.PID);
            if (prj == null) return NotFound();
            prj.Name = pData.ProjectData.Header.ProjectName;
            prj.Description = pData.ProjectData.Header.ProjectDescription;
            prj.Tooltip = pData.ProjectData.Header.ProjectTooltip;
            if (pData.ImgFile != null)
            {
                prj.ImgRef = UploadImage(pData.ImgFile);
            }
            _DBContext.SaveChanges();
            return RedirectToAction("ViewProject", new { pPID = pData.ProjectData.PID });
        }


        [HttpGet]
        public IActionResult EditTabs(int pPID)
        {
            var prj = _DBContext.Projects.Where(p => p.Pid == pPID).Include(p => p.ProjectTabs);
            if (prj == null) return NotFound();

            var aux = ProjectDataAdapter.ProjectTabsFromRow(prj.First());
            return View(aux);
        }

        [HttpPost]
        public IActionResult EditTabs(int PID, int tabcount)
        {
            var prj = _DBContext.Projects.Find(PID);
            if (prj == null) return NotFound();
            var tabs = _DBContext.ProjectTabs.Where(t => t.Pid == PID).ToList();
            foreach (var tab in tabs)
            {
                var newName = Request.Form[$"Tab-{tab.Tid}"];
                if (!string.IsNullOrEmpty(newName))
                {
                    tab.Name = newName;
                }
            }
            _DBContext.SaveChanges();
            return RedirectToAction("ViewProject", new { pPID = PID });
        }


        [HttpGet]
        public IActionResult EditSection(int pPID, int pTID, int pSID)
        {
            var section = _DBContext.ContentSections.Find(pPID, pTID, pSID);
            if (section == null) return NotFound();
            var aux = new ViewSectionData();
            aux.PID = pPID;
            aux.TID = pTID;
            aux.section = ContentSectionDataAdapter.SectionObjectFromRow(section);
            return View(aux);
        }

        [HttpPost]
        public IActionResult EditSection(ViewSectionData pData)
        {
            var section = _DBContext.ContentSections.Find(pData.PID, pData.TID, pData.section.SID);
            if (section == null) return NotFound();
            section.Name = pData.section.SectionName;
            section.Tooltip = pData.section.SectionTooltip;
            _DBContext.SaveChanges();
            return RedirectToAction("ViewProject", new { pPID = pData.PID, pTID = pData.TID });
        }

        [HttpGet]
        public IActionResult EditItem(int pPID, int pTID, int pSID, int pIID)
        {
            var item = _DBContext.ContentItems.Find(pPID, pTID, pSID, pIID);
            if (item == null) return NotFound();

            var cim = _DBContext.ContentSingleImages.ToList();
            var csc = _DBContext.ContentSingleComparisons.ToList();
            var cinf = _DBContext.ComparisonItemInfos.ToList();

            var aux = ContentItemDataAdapter.DataObjectFromItemRow(item);
            
            
            ViewBag.ItemType = item.Type;
            return View(aux);
        }

        [HttpPost]
        public IActionResult EditItem(ViewItemData pData)
        {
            if (pData.ItemData.IID == 0)
            {
                pData.ItemData.IID = Int32.Parse(Request.Form["ItemData.IID"]);
            }
            var item = _DBContext.ContentItems.Find(pData.PID, pData.TID, pData.SID, pData.ItemData.IID);
            if (item == null) return NotFound();
            item.Title = pData.ItemData.ItemTitle;
            item.Text = pData.ItemData.ItemText;

TPI-ProjectPresenter/Views/Project/DeleteProject.cshtml
@model TPI_ProjectPresenter.Models.DataTx.ViewProjectEntityData;

@{
    ViewData["Title"] = "DeleteProject";
}

<div class="container-lg">
    <div class="text-center"><h1>Delete Project</h1></div>
    <div class="row">
        <form class="form-floating mb-3" asp-controller="Project" asp-action="DeleteProject" method="post" enctype="multipart/form-data">
            <input type="hidden" name="ProjectData.PID" asp-for="ProjectData.PID" value="@Model.ProjectData.PID" />
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectName" class="form-label">Name: </label>
                <input name="ProjectData.Header.ProjectName" disabled class="form-control form-text" type="text" asp-for="ProjectData.Header.ProjectName" />
            </div>
            <div class="col-8 offset-lg-2">
                <div class="row">
                    <div class="col-3">
                        <img class="img-fluid float-start ProjectImage" src="/img/@Model.ProjectData.Header.ProjectImgRef" />
                    </div>
                </div>
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectDescription" class="form-label">Project Description: </label>
                <textarea id="ProjectDescription" name="ProjectData.Header.ProjectDescription" disabled class="form-control" rows="5" asp-for="ProjectData.Header.ProjectDescription"> </textarea>
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectTooltip" class="form-label">Project Tooltip: </label>
                <textarea id="ProjectTooltip" name="ProjectData.Header.ProjectTooltip" disabled class="form-control" rows="5" asp-for="ProjectData.Header.ProjectTooltip"> </textarea>
            </div>
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>
        </form>
    </div>
</div>

TPI-ProjectPresenter/Views/Project/DeleteSection.cshtml
@model TPI_ProjectPresenter.Models.DataTx.ViewSectionData;

@{
    ViewData["Title"] = "DeleteSection";
}

<div class="container-lg">
    <div class="text-center"><h1>Delete Section</h1></div>
    <div class="row">
        <form class="form-floating mb-3" asp-controller="Project" asp-action="DeleteSection" method="post" enctype="multipart/form-data">
            <input type="hidden" name="PID" asp-for="PID" value="@Model.PID" />
            <input type="hidden" name="TID" asp-for="TID" value="@Model.TID" />
            <input type="hidden" name="section.SID" asp-for="section.SID" value="@Model.section.SID" />
            <div class="col-8 offset-lg-2">
                <label asp-for="section.SectionName" class="form-label">Name: </label>
                <input name="section.SectionName" disabled class="form-control form-text" type="text" asp-for="section.SectionName" />
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="section.SectionTooltip" class="form-label">Tooltip: </label>
                <textarea id="SectionToolTip" name="section.SectionTooltip" disabled class="form-control" rows="5" asp-for="section.SectionTooltip"> </textarea>
            </div>
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>
        </form>
    </div>
</div>

TPI-ProjectPresenter/Views/Project/EditItem.cshtml
@model TPI_ProjectPresenter.Models.DataTx.ViewItemData;

@{
    ViewData["Title"] = "EditItem";

    var itemType = ViewBag.ItemType;
}

@section Scripts
{
    
}

<div class="container-lg">
    <div class="text-center"><h1>Edit @ViewBag.ItemType Item</h1></div>
    <form class="form-floating mb-3" asp-controller="Project" asp-action="EditItem" method="post" enctype="multipart/form-data">
        <div class="row">
            <input type="hidden" name="PID" asp-for="PID" value="@Model.PID" />
            <input type="hidden" name="TID" asp-for="TID" value="@Model.TID" />
            <input type="hidden" name="SID" asp-for="SID" value="@Model.SID" />
            <input type="hidden" name="ItemData.IID" asp-for="ItemData.IID" value="@Model.ItemData.IID" />
            <input type="hidden" name="ItemData.ItemType" asp-for="ItemData.ItemType" value="@Model.ItemData.ItemType" />
            <div class="col-8 offset-lg-2">
                <label asp-for="ItemData.ItemTitle" class="form-label">Item Title: </label>
                <input name="ItemData.ItemTitle" class="form-control form-text" type="text" asp-for="ItemData.ItemTitle" />
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ItemData.ItemText" class="form-label">Item Text: </label>
                <textarea id="ItemData.ItemText" name="ItemData.ItemText" class="form-control" rows="5" asp-for="ItemData.ItemText"> </textarea>
            </div>
            <div class="col-8 offset-lg-2">
                <label class="form-label">Type: </label>
                <input class="form-control form-text" type="text" disabled value="@Model.ItemData.ItemType" />
            </div>
        </div>

        @switch (itemType)
        {
            case "TextOnly":
                <div class="row itemdetail" id="TextOnly">
                </div>
                break;
			case "SingleImage":
                <div class="row itemdetail" id="SingleImage">
                    <div class="col-8 offset-lg-2">
                        <div class="row">
                            <div class="col-3">
                                <img class="img-fluid float-start ProjectImage" src="/img/@Model.ImgRef" />
                            </div>
                            <div class="col-lg-9 col-sm-5">
                                <label asp-for="ImgFile" class="form-label">Change Image: </label>
                                <input name="ImgFile" type="file" class="form-control" asp-for="ImgFile" />
                            </div>
                        </div>
                    </div>
                </div>
                break;
            case "SingleComparison":
                <div class="row itemdetail" id="SingleComparison">
                    <div class="col-8 offset-lg-2">
                        <div class="row">
                            <div class="col-4 offset-lg-1">
                                <div class="row">
                                    <label asp-for="SingleComparisonData.LeftItem.ItemTitle">Left Title:</label>
                                    <input name="SingleComparisonData.LeftItem.ItemTitle" class="form-control form-text" type="text" asp-for="SingleComparisonData.LeftItem.ItemTitle" />
                                </div>
                                <div class="row">
                                    <label asp-for="SingleComparisonData.LeftItem.ItemDetail">Left Detail:</label>
                                    <textarea id="SingleComparisonData.LeftItem.ItemDetail" name="SingleComparisonData.LeftItem.ItemDetail" class="form-control" rows="5" asp-for="SingleComparisonData.LeftItem.ItemDetail"> </textarea>
                                </div>
                                @{ int i = 1; }
                                @foreach (var info in Model.SingleComparisonData.LeftItem.ItemizedInfo)
                                {
                                    <div class="row">
                                        <label>Info-@i</label>
                                        <input name="LItemInfo-@i" class="form-control form-text" type="text" value="@info" />
                                    </div>
									i++;
                                }
                            </div>
                            <div class="col-4 offset-lg-2">
                                <div class="row">
                                    <label asp-for="SingleComparisonData.RightItem.ItemTitle">Right Title:</label>
                                    <input name="SingleComparisonData.RightItem.ItemTitle" class="form-control form-text" type="text" asp-for="SingleComparisonData.RightItem.ItemTitle" />
                                </div>
                                <div class="row">
                                    <label asp-for="SingleComparisonData.RightItem.ItemDetail">Right Detail:</label>
                                    <textarea id="SingleComparisonData.RightItem.ItemDetail" name="SingleComparisonData.RightItem.ItemDetail" class="form-control" rows="5" asp-for="SingleComparisonData.RightItem.ItemDetail"> </textarea>
                                </div>
                                @{ i = 1; }
                                @foreach (var info in Model.SingleComparisonData.RightItem.ItemizedInfo)
                                {
                                    <div class="row">
                                        <label>Info-@i</label>
                                        <input name="RItemInfo-@i" class="form-control form-text" type="text" value="@info" />
                                    </div>
									i++;
                                }
                            </div>
                        </div>
                    </div>
                </div>
                break;

        }
        <div class="row">
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>

    </form>
</div>

TPI-ProjectPresenter/Views/Project/EditProject.cshtml
@model TPI_ProjectPresenter.Models.DataTx.ViewProjectEntityData;

@{
    ViewData["Title"] = "EditProject";
}

<div class="container-lg">
    <div class="text-center"><h1>Edit Project</h1></div>
    <div class="row">
        <form class="form-floating mb-3" asp-controller="Project" asp-action="EditProject" method="post" enctype="multipart/form-data">
            <input type="hidden" name="ProjectData.PID" asp-for="ProjectData.PID" value="@Model.ProjectData.PID" />
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectName" class="form-label">Name: </label>
                <input name="ProjectData.Header.ProjectName" class="form-control form-text" type="text" asp-for="ProjectData.Header.ProjectName" />
            </div>
            <div class="col-8 offset-lg-2">
				<div class="row">
                    <div class="col-3">
                        <img class="img-fluid float-start ProjectImage" src="/img/@Model.ProjectData.Header.ProjectImgRef"/>
                    </div>
                    <div class="col-lg-9 col-sm-5">
                        <label asp-for="ImgFile" class="form-label">Change Image: </label>
                        <input name="ImgFile" type="file" class="form-control" asp-for="ImgFile" />
                    </div>
                </div>
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectDescription" class="form-label">Project Description: </label>
                <textarea id="ProjectDescription" name="ProjectData.Header.ProjectDescription" class="form-control" rows="5" asp-for="ProjectData.Header.ProjectDescription"> </textarea>
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectTooltip" class="form-label">Project Tooltip: </label>
                <textarea id="ProjectTooltip" name="ProjectData.Header.ProjectTooltip" class="form-control" rows="5" asp-for="ProjectData.Header.ProjectTooltip"> </textarea>
            </div>
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-primary" type="submit">Edit</button>
            </div>
        </form>
    </div>
</div>

TPI-ProjectPresenter/Views/Project/EditSection.cshtml
@model TPI_ProjectPresenter.Models.DataTx.ViewSectionData;

@{
    ViewData["Title"] = "EditSection";
}

<div class="container-lg">
    <div class="text-center"><h1>Edit Section</h1></div>
    <div class="row">
        <form class="form-floating mb-3" asp-controller="Project" asp-action="EditSection" method="post" enctype="multipart/form-data">
            <input type="hidden" name="PID" asp-for="PID" value="@Model.PID" />
            <input type="hidden" name="TID" asp-for="TID" value="@Model.TID" />
            <input type="hidden" name="section.SID" asp-for="section.SID" value="@Model.section.SID" />
            <div class="col-8 offset-lg-2">
                <label asp-for="section.SectionName" class="form-label">Name: </label>
                <input name="section.SectionName" class="form-control form-text" type="text" asp-for="section.SectionName" />
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="section.SectionTooltip" class="form-label">Tooltip: </label>
                <textarea id="SectionToolTip" name="section.SectionTooltip" class="form-control" rows="5" asp-for="section.SectionTooltip"> </textarea>
            </div>
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-primary" type="submit">Edit</button>
            </div>
        </form>
    </div>
</div>

TPI-ProjectPresenter/Views/Project/EditTabs.cshtml
@model TPI_ProjectPresenter.Models.Projects.ProjectEntity;

@{
    ViewData["Title"] = "EditTabs";
}

@section Scripts
{
    <script>
        var tabrows = document.querySelectorAll(".delBtn");

        for (var row of tabrows) {
            row.addEventListener("click", function () {
                var tid = this.getAttribute("data-tid");
                var name = this.getAttribute("data-name");
                LoadInfo(tid, name);
            });
        }

        function LoadInfo(tid, name) 
        {
            document.getElementById("modalTabName").value = name;
            document.getElementById("modalTID").value = tid
            return false;
        }
    </script>
}

<div class="container-lg">
    <div class="text-center"><h1>Edit Project Tabs</h1></div>
    <div class="row">
        <form class="form-floating mb-3" asp-controller="Project" asp-action="EditTabs" method="post" enctype="multipart/form-data">
            <input type="hidden" name="PID" asp-for="PID" value="@Model.PID" />
            @foreach (var tab in Model.GetTabs())
            {
                <div class="row">
                    <div class="col-7 offset-lg-2">
                        <label class="form-label">Tab @tab.TID Name: </label>
                        <input name="Tab-@tab.TID" class="form-control form-text" type="text" value="@tab.TabName"/>
                    </div>
                    <div class="col-1 row-cols-2 align-content-center">
                        <button type="button" class="btn-sm btn-danger delBtn" data-bs-toggle="modal" data-bs-target="#delTabModal" data-tid="@tab.TID" data-name="@tab.TabName"><i class="bi bi-folder-minus"></i></button>
                    </div>
                </div>
			}            
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-primary" type="submit">Edit</button>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="delTabModal" tabindex="-1" aria-labelledby="delTabModalLabel" aria-hidden="true">​
    <div class="modal-dialog">​
        <div class="modal-content">​
            <div class="modal-header">​
                <h1 class="modal-title fs-5" id="delTabModalLabel">Delete Tab Modal</h1>​
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>​
            </div>​
            <form class="form-floating mb-3" asp-controller="Project" asp-action="DeleteTab">
                <input type="hidden" name="PID" value="@Model.PID" />
                <input id="modalTID" type="hidden" name="TID" value="" />
                <div class="modal-body">​                
                    <label class="form-label">Name: </label>
                    <input id="modalTabName" name="TabName" disabled class="form-control form-text" type="text" value=""/>
                </div>​
                <div class="modal-footer">​
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>​
                    <button type="submit" class="btn btn-danger" >Delete</button>​
                </div>​
            </form>
        </div>​
    </div>​
</div>

TPI-ProjectPresenter/Views/Project/NewProject.cshtml
@model TPI_ProjectPresenter.Models.DataTx.ViewProjectEntityData;

@{
    ViewData["Title"] = "NewProject";
}

<div class="container-lg">
    <div class="text-center"><h1>New Project</h1></div>
    <div class="row">
        <form class="form-floating mb-3" asp-controller="Project" asp-action="NewProject" method="post" enctype="multipart/form-data">
            <input type="hidden" name="ProjectData.PID" asp-for="ProjectData.PID" value="@Model.ProjectData.PID" />
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectName" class="form-label">Name: </label>
                <input name="ProjectData.Header.ProjectName" class="form-control form-text" type="text" asp-for="ProjectData.Header.ProjectName" />
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectDescription" class="form-label">Project Image: </label>
                <input name="ImgFile" type="file" class="form-control" asp-for="ImgFile" />
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectDescription" class="form-label">Project Description: </label>
                <textarea id="ProjectDescription" name="ProjectData.Header.ProjectDescription" class="form-control" rows="5" asp-for="ProjectData.Header.ProjectDescription"> </textarea>
            </div>
            <div class="col-8 offset-lg-2">
                <label asp-for="ProjectData.Header.ProjectTooltip" class="form-label">Project Tooltip: </label>
                <textarea id="ProjectTooltip" name="ProjectData.Header.ProjectTooltip" class="form-control" rows="5" asp-for="ProjectData.Header.ProjectTooltip"> </textarea>
            </div>
            <div class="col-2 offset-lg-8 offset-sm-4 align-content-end">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>
    </div>
</div>